import { VehicleRepository } from "../repositories/vehicle.repository";
import { ReservationRepository } from "../repositories/reservation.repository";
import { AvailabilityEngine } from "./availability.engine";
import { VehicleAllocationStrategy } from "./vehicle-allocation.strategy";
import { Reservation } from "../models/reservation";

interface ReserveVehicleInput {
  vehicleId?: string; // Optional if we want the system to allocate automatically
  location: string;
  vehicleType: string;
  startDateTime: Date;
  durationMins: number;
  customerName: string;
  customerEmail: string;
  customerPhone: string;
}

export class ReserveVehicleUseCase {
  constructor(
    private readonly vehicleRepository: VehicleRepository,
    private readonly reservationRepository: any, // Cast to any or a custom TransactionalRepository to support sessions
    private readonly availabilityEngine: AvailabilityEngine,
    private readonly allocationStrategy: VehicleAllocationStrategy
  ) {}

  /**
   * Orchestrates the reservation process.
   * 
   * Process:
   * 1. Find all vehicles of the requested type and location.
   * 2. Filter vehicles that are actually available for the requested slot.
   * 3. Use the Allocation Strategy to pick the best vehicle (Even Distribution).
   * 4. Save the reservation.
   * 
   * Note: Concurrency is handled by a distributed lock at the controller level.
   */
  async execute(input: ReserveVehicleInput): Promise<Reservation> {
    const { location, vehicleType, startDateTime, durationMins, customerName, customerEmail, customerPhone } = input;
    
    const endDateTime = new Date(startDateTime.getTime() + durationMins * 60000);

    // 1. Find eligible vehicles
    const candidates = await this.vehicleRepository.findEligibleVehicles(vehicleType, location);
    
    if (candidates.length === 0) {
      throw new Error("No vehicles of this type available at the requested location.");
    }

    // 2. Filter by actual availability (Operating hours, 14-day window, overlaps)
    const availableVehicles = [];
    for (const vehicle of candidates) {
      const reservations = await this.reservationRepository.findByVehicleId(vehicle.id);
      if (this.availabilityEngine.isVehicleAvailable(vehicle, startDateTime, endDateTime, reservations)) {
        availableVehicles.push(vehicle);
      }
    }

    if (availableVehicles.length === 0) {
      throw new Error("No vehicles are available for the requested time slot.");
    }

    // 3. Allocate the best vehicle using the strategy (Even Distribution)
    const usageMap = await this.reservationRepository.countReservationsByVehicle(
      availableVehicles.map(v => v.id)
    );
    
    const selectedVehicle = this.allocationStrategy.selectVehicle(availableVehicles, usageMap);

    if (!selectedVehicle) {
      throw new Error("Failed to allocate a vehicle.");
    }

    // 4. Create and save the reservation
    const reservation: Reservation = {
      id: undefined as any, // ID will be generated by MongoDB
      vehicleId: selectedVehicle.id,
      startDateTime,
      endDateTime,
      customerName,
      customerEmail,
      customerPhone,
    };

    await this.reservationRepository.save(reservation);

    return reservation;
  }
}
